### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [stape-io/xandr-tag#1]
https://github.com/stape-io/xandr-tag/blob/b20a63089ace2064f8c58fcd977be46b14df7180/template.tpl#L220-L224

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by Bukashk0zzz** [comment]
Thanks. 
fixed https://github.com/stape-io/xandr-tag/commit/f4db1ac7c250f89ea264b708d874d6bc5371c5b1
